name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - output_target: linux-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-musl

          - output_target: linux-aarch64
            os: ubuntu-22.04
            target: aarch64-unknown-linux-musl
            container: ghcr.io/cross-rs/aarch64-unknown-linux-musl:edge

          - output_target: win-x86_64
            os: windows-2022
            target: x86_64-pc-windows-msvc
            output_postfix: '.exe'

          - output_target: darwin-x86_64
            os: macOS-12
            target: x86_64-apple-darwin

          - output_target: darwin-aarch64
            os: macOS-12
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt install -y musl-tools

      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch
        run: cargo fetch --target ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
        env:
          RUSTFLAGS: "-C opt-level=3 -C lto=true -C embed-bitcode=true -C strip=symbols -C codegen-units=1 -C target-feature=+crt-static ${{ matrix.target_flags }}"

      - name: Prepare
        run: mv "target/${{ matrix.target }}/release/${{ github.event.repository.name }}${{ matrix.output_postfix }}" "${{ github.event.repository.name }}-${{ matrix.output_target }}${{ matrix.output_postfix }}"

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "${{ github.event.repository.name }}-${{ matrix.output_target }}${{ matrix.output_postfix }}"
