name: Update flake

on:
  release:
    types: [published]
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  update-flake:
    name: Update flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - uses: cachix/install-nix-action@v20
      - name: Update flake
        run: |
          for url in $(grep -oP 'https://.*?\?' flake.nix)
          do
            new_url="$(echo "$url" | sed 's#v[0-9]*\.[0-9]*\.[0-9]*#${{ github.event.release.tag_name }}#')"
            hash="$(curl -L -o - "$new_url" | sha256sum | grep -o '[A-Za-z0-9]*')"
            sed -i "s#\"$url\?.*\"#\"$new_url$hash\"#" flake.nix
          done
      - name: Try build
        run: |
          nix build .#
          result/bin/random 0 1
          rm result
      - name: Commit update
        run: |
          git add flake.nix flake.lock
          git config --global user.name 'Flake updater'
          git config --global user.email 'flake-updater@flake-updater'
          git commit -m 'Automated flake update'
          git push origin main

